baseurl = "https://jens.dev/"
title = "My personal blog"
theme = "ghostwriter"
languageCode = "en-us"
googleAnalytics = "UA-5676095-8"
Paginate=999 
uglyurls = true
publishDir = "docs"

[privacy.googleAnalytics]
anonymizeIP = true
respectDoNotTrack = true
useSessionStorage = false

[taxonomies]
tag = "tags"

[Params]
  mainSections = ["post"]
  intro = true
  headline = ""
  description = ""
  github = "https://github.com/JensWalter"
  mastodon = "https://hachyderm.io/@jenswalter"
  opengraph = true
  rss = true

[Permalinks]
  post = "/:year/:month/:day/:filename"

[markup.highlight]
  style = "monokailight"

[menu]
main = [ 
{ name= "Blog",url= "/", weight= 1},
{ name= "Projects", url= "/project.html", weight= 2}
]
